<?php

/**
 * This is the model base class for the table "DeviceList".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DeviceList".
 *
 * Columns in table "DeviceList" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $accountID
 * @property string $groupID
 * @property string $deviceID
 * @property string $lastUpdateTime
 * @property string $creationTime
 *
 */
abstract class BaseDeviceList extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'DeviceList';
    }

    public static function representingColumn() {
        return 'accountID';
    }

    public function rules() {
        return array(
            array('accountID, groupID, deviceID', 'required'),
            array('accountID, groupID, deviceID', 'length', 'max'=>32),
            array('lastUpdateTime, creationTime', 'length', 'max'=>10),
            array('lastUpdateTime, creationTime', 'default', 'setOnEmpty' => true, 'value' => null),
            array('accountID, groupID, deviceID, lastUpdateTime, creationTime', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'accountID' => Yii::t('app', 'Account'),
                'groupID' => Yii::t('app', 'Group'),
                'deviceID' => Yii::t('app', 'Device'),
                'lastUpdateTime' => Yii::t('app', 'Last Update Time'),
                'creationTime' => Yii::t('app', 'Creation Time'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('accountID', $this->accountID, true);
        $criteria->compare('groupID', $this->groupID, true);
        $criteria->compare('deviceID', $this->deviceID, true);
        $criteria->compare('lastUpdateTime', $this->lastUpdateTime, true);
        $criteria->compare('creationTime', $this->creationTime, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}