<?php

/**
 * This is the model base class for the table "SystemAudit".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SystemAudit".
 *
 * Columns in table "SystemAudit" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $accountID
 * @property integer $auditTime
 * @property integer $auditCode
 * @property string $userID
 * @property string $deviceID
 * @property string $ipAddress
 * @property string $privateLabelName
 * @property string $description
 * @property string $notes
 * @property string $creationTime
 *
 */
abstract class BaseSystemAudit extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'SystemAudit';
    }

    public static function representingColumn() {
        return 'accountID';
    }

    public function rules() {
        return array(
            array('accountID, auditTime, auditCode', 'required'),
            array('auditTime, auditCode', 'numerical', 'integerOnly'=>true),
            array('accountID, userID, deviceID, ipAddress, privateLabelName', 'length', 'max'=>32),
            array('description', 'length', 'max'=>128),
            array('creationTime', 'length', 'max'=>10),
            array('notes', 'safe'),
            array('userID, deviceID, ipAddress, privateLabelName, description, notes, creationTime', 'default', 'setOnEmpty' => true, 'value' => null),
            array('accountID, auditTime, auditCode, userID, deviceID, ipAddress, privateLabelName, description, notes, creationTime', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'accountID' => Yii::t('app', 'Account'),
                'auditTime' => Yii::t('app', 'Audit Time'),
                'auditCode' => Yii::t('app', 'Audit Code'),
                'userID' => Yii::t('app', 'User'),
                'deviceID' => Yii::t('app', 'Device'),
                'ipAddress' => Yii::t('app', 'Ip Address'),
                'privateLabelName' => Yii::t('app', 'Private Label Name'),
                'description' => Yii::t('app', 'Description'),
                'notes' => Yii::t('app', 'Notes'),
                'creationTime' => Yii::t('app', 'Creation Time'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('accountID', $this->accountID, true);
        $criteria->compare('auditTime', $this->auditTime);
        $criteria->compare('auditCode', $this->auditCode);
        $criteria->compare('userID', $this->userID, true);
        $criteria->compare('deviceID', $this->deviceID, true);
        $criteria->compare('ipAddress', $this->ipAddress, true);
        $criteria->compare('privateLabelName', $this->privateLabelName, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('notes', $this->notes, true);
        $criteria->compare('creationTime', $this->creationTime, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}