<?php

/**
 * This is the model base class for the table "DeviceGroup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DeviceGroup".
 *
 * Columns in table "DeviceGroup" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $accountID
 * @property string $groupID
 * @property string $displayName
 * @property string $description
 * @property string $notes
 * @property string $lastUpdateTime
 * @property string $creationTime
 *
 */
abstract class BaseDeviceGroup extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'DeviceGroup';
    }

    public static function representingColumn() {
        return 'accountID';
    }

    public function rules() {
        return array(
            array('accountID, groupID', 'required'),
            array('accountID, groupID', 'length', 'max'=>32),
            array('displayName', 'length', 'max'=>40),
            array('description', 'length', 'max'=>128),
            array('lastUpdateTime, creationTime', 'length', 'max'=>10),
            array('notes', 'safe'),
            array('displayName, description, notes, lastUpdateTime, creationTime', 'default', 'setOnEmpty' => true, 'value' => null),
            array('accountID, groupID, displayName, description, notes, lastUpdateTime, creationTime', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'accountID' => Yii::t('app', 'Account'),
                'groupID' => Yii::t('app', 'Group'),
                'displayName' => Yii::t('app', 'Display Name'),
                'description' => Yii::t('app', 'Description'),
                'notes' => Yii::t('app', 'Notes'),
                'lastUpdateTime' => Yii::t('app', 'Last Update Time'),
                'creationTime' => Yii::t('app', 'Creation Time'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('accountID', $this->accountID, true);
        $criteria->compare('groupID', $this->groupID, true);
        $criteria->compare('displayName', $this->displayName, true);
        $criteria->compare('description', $this->description, true);
        $criteria->compare('notes', $this->notes, true);
        $criteria->compare('lastUpdateTime', $this->lastUpdateTime, true);
        $criteria->compare('creationTime', $this->creationTime, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}