<?php

/**
 * This is the model base class for the table "UnassignedDevices".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UnassignedDevices".
 *
 * Columns in table "UnassignedDevices" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $serverID
 * @property string $mobileID
 * @property string $timestamp
 * @property string $ipAddress
 * @property integer $isDuplex
 * @property double $latitude
 * @property double $longitude
 * @property string $data
 * @property string $creationTime
 *
 */
abstract class BaseUnassignedDevices extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'UnassignedDevices';
    }

    public static function representingColumn() {
        return 'serverID';
    }

    public function rules() {
        return array(
            array('serverID, mobileID', 'required'),
            array('isDuplex', 'numerical', 'integerOnly'=>true),
            array('latitude, longitude', 'numerical'),
            array('serverID, mobileID, ipAddress', 'length', 'max'=>32),
            array('timestamp, creationTime', 'length', 'max'=>10),
            array('data', 'length', 'max'=>255),
            array('timestamp, ipAddress, isDuplex, latitude, longitude, data, creationTime', 'default', 'setOnEmpty' => true, 'value' => null),
            array('serverID, mobileID, timestamp, ipAddress, isDuplex, latitude, longitude, data, creationTime', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'serverID' => Yii::t('app', 'Server'),
                'mobileID' => Yii::t('app', 'Mobile'),
                'timestamp' => Yii::t('app', 'Timestamp'),
                'ipAddress' => Yii::t('app', 'Ip Address'),
                'isDuplex' => Yii::t('app', 'Is Duplex'),
                'latitude' => Yii::t('app', 'Latitude'),
                'longitude' => Yii::t('app', 'Longitude'),
                'data' => Yii::t('app', 'Data'),
                'creationTime' => Yii::t('app', 'Creation Time'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('serverID', $this->serverID, true);
        $criteria->compare('mobileID', $this->mobileID, true);
        $criteria->compare('timestamp', $this->timestamp, true);
        $criteria->compare('ipAddress', $this->ipAddress, true);
        $criteria->compare('isDuplex', $this->isDuplex);
        $criteria->compare('latitude', $this->latitude);
        $criteria->compare('longitude', $this->longitude);
        $criteria->compare('data', $this->data, true);
        $criteria->compare('creationTime', $this->creationTime, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'CTimestampBehavior' => array(
                'class' => 'zii.behaviors.CTimestampBehavior',
                'createAttribute' => null,
                'updateAttribute' => 'timestamp',
                'timestampExpression' => new CDbExpression('NOW()'),
            )
        ), parent::behaviors());
    }
}