<?php

/**
 * This is the model base class for the table "SessionStats".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SessionStats".
 *
 * Columns in table "SessionStats" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $accountID
 * @property string $deviceID
 * @property string $timestamp
 * @property string $ipAddress
 * @property integer $isDuplex
 * @property string $bytesRead
 * @property string $bytesWritten
 * @property string $bytesOverhead
 * @property string $bytesRounded
 * @property string $eventsReceived
 * @property string $creationTime
 *
 */
abstract class BaseSessionStats extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'SessionStats';
    }

    public static function representingColumn() {
        return 'accountID';
    }

    public function rules() {
        return array(
            array('accountID, deviceID', 'required'),
            array('isDuplex', 'numerical', 'integerOnly'=>true),
            array('accountID, deviceID, ipAddress', 'length', 'max'=>32),
            array('timestamp, bytesRead, bytesWritten, bytesOverhead, bytesRounded, eventsReceived, creationTime', 'length', 'max'=>10),
            array('ipAddress, isDuplex, bytesRead, bytesWritten, bytesOverhead, bytesRounded, eventsReceived, creationTime', 'default', 'setOnEmpty' => true, 'value' => null),
            array('accountID, deviceID, timestamp, ipAddress, isDuplex, bytesRead, bytesWritten, bytesOverhead, bytesRounded, eventsReceived, creationTime', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'accountID' => Yii::t('app', 'Account'),
                'deviceID' => Yii::t('app', 'Device'),
                'timestamp' => Yii::t('app', 'Timestamp'),
                'ipAddress' => Yii::t('app', 'Ip Address'),
                'isDuplex' => Yii::t('app', 'Is Duplex'),
                'bytesRead' => Yii::t('app', 'Bytes Read'),
                'bytesWritten' => Yii::t('app', 'Bytes Written'),
                'bytesOverhead' => Yii::t('app', 'Bytes Overhead'),
                'bytesRounded' => Yii::t('app', 'Bytes Rounded'),
                'eventsReceived' => Yii::t('app', 'Events Received'),
                'creationTime' => Yii::t('app', 'Creation Time'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('accountID', $this->accountID, true);
        $criteria->compare('deviceID', $this->deviceID, true);
        $criteria->compare('timestamp', $this->timestamp, true);
        $criteria->compare('ipAddress', $this->ipAddress, true);
        $criteria->compare('isDuplex', $this->isDuplex);
        $criteria->compare('bytesRead', $this->bytesRead, true);
        $criteria->compare('bytesWritten', $this->bytesWritten, true);
        $criteria->compare('bytesOverhead', $this->bytesOverhead, true);
        $criteria->compare('bytesRounded', $this->bytesRounded, true);
        $criteria->compare('eventsReceived', $this->eventsReceived, true);
        $criteria->compare('creationTime', $this->creationTime, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
            'CTimestampBehavior' => array(
                'class' => 'zii.behaviors.CTimestampBehavior',
                'createAttribute' => null,
                'updateAttribute' => 'timestamp',
                'timestampExpression' => new CDbExpression('NOW()'),
            )
        ), parent::behaviors());
    }
}