<?php /** @var Device $model */
$this->breadcrumbs=array(
	'Devices'=>array('index'),
	$model->id,
);

$this->menu=array(
    //array('label' => Yii::t('AweCrud.app', 'List').' '.Device::label(2), 'icon' => 'list', 'url' => array('index')),
    array('label' => Yii::t('AweCrud.app', 'Create').' Device', 'icon' => 'plus', 'url' => array('create')),
	array('label' => Yii::t('AweCrud.app', 'Update'), 'icon' => 'pencil', 'url' => array('update', 'id' => $model->id)),
    array('label' => Yii::t('AweCrud.app', 'Delete'), 'icon' => 'trash', 'url' => '#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm' => Yii::t('AweCrud.app', 'Are you sure you want to delete this item?'))),
    array('label' => Yii::t('AweCrud.app', 'Manage'), 'icon' => 'list-alt', 'url' => array('admin')),
);
?>

<fieldset>
    <legend><?php echo Yii::t('AweCrud.app', 'View') ?> Device <?php echo CHtml::encode($model) ?></legend>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data' => $model,
	'attributes' => array(
        'accountID',
        'deviceID',
        'groupID',
        'equipmentType',
        'vehicleID',
        'licensePlate',
        'driverID',
        'fuelCapacity',
        'fuelEconomy',
        'speedLimitKPH',
        'planDistanceKM',
        'expirationTime',
        'uniqueID',
        'deviceCode',
        'deviceType',
        'dcsPropertiesID',
        'pushpinID',
        'displayColor',
        'serialNumber',
        'simPhoneNumber',
        'smsEmail',
        'imeiNumber',
        'dataKey',
        'ignitionIndex',
        'codeVersion',
        'featureSet',
        'ipAddressValid',
        'lastTotalConnectTime',
        'lastDuplexConnectTime',
        'pendingPingCommand',
        'lastPingTime',
        'totalPingCount',
        'maxPingCount',
        'expectAck',
        'lastAckCommand',
        'lastAckTime',
        'dcsConfigMask',
        'supportsDMTP',
        'supportedEncodings',
        'unitLimitInterval',
        'maxAllowedEvents',
        'totalProfileMask',
        'totalMaxConn',
        'totalMaxConnPerMin',
        'duplexProfileMask',
        'duplexMaxConn',
        'duplexMaxConnPerMin',
        'ipAddressCurrent',
        'remotePortCurrent',
        'listenPortCurrent',
        'lastInputState',
        'lastBatteryLevel',
        'lastFuelLevel',
        'lastFuelTotal',
        'lastOilLevel',
        'lastValidLatitude',
        'lastValidLongitude',
        'lastValidHeading',
        'lastGPSTimestamp',
        'lastCellServingInfo',
        'lastOdometerKM',
        'odometerOffsetKM',
        'lastEngineHours',
        'engineHoursOffset',
        'lastIgnitionOnTime',
        'lastIgnitionOffTime',
        'isActive',
        'displayName',
        'description',
        'notes',
        'lastUpdateTime',
        'creationTime',
        'simID',
        'lastTcpSessionID',
        'lastEventTimestamp',
        'lastStopTime',
        'lastStartTime',
        'lastMalfunctionLamp',
        'lastFaultCode',
        'allowNotify',
        'lastNotifyTime',
        'lastNotifyCode',
        'notifyEmail',
        'notifySelector',
        'notifyAction',
        'notifyDescription',
        'notifySubject',
        'notifyText',
        'notifyUseWrapper',
        'notifyPriority',
        'parkedLatitude',
        'parkedLongitude',
        'parkedRadius',
        'lastDataPushTime',
        'lastEventCreateMillis',
        'id',
	),
)); ?>
</fieldset>